# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

target 'Sea Stars' do
    pod 'Firebase'
    pod 'IQKeyboardManagerSwift'
    pod 'DZNEmptyDataSet'
    pod 'AFNetworking'

end

